In [1]:
import pandas as pd

# 1. Read a .csv from a URL with Pandas

#### Target websites : https://www.football-data.co.uk/data.php

In [2]:
# reading 1 csv from the website
df_premier2021 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [3]:
# Showing DataFrame
df_premier2021

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [4]:
# rename columns
df_premier2021.rename(columns={'FTHG':'Home_goals','FTAG':'Away_goals'} ,inplace = True)

In [5]:
#show Data frame
df_premier2021

,Div,Date,Time,HomeTeam,AwayTeam,Home_goals,Away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

# 2 .csv from multiple URLs with pandas

https://www.football-data.co.uk/mmz4281/2122/E0.csv
https://www.football-data.co.uk/mmz4281/2122/E1.csv

#### Link : root + season + leagues

In [6]:
# link structure
"https://www.football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2122/E0.csv'

In [7]:
# Create a root Variables 
root = "https://www.football-data.co.uk/mmz4281/"

# 2.1 Multiple Leagues
##### https://www.football-data.co.uk/mmz4281/2122/E0.csv
##### https://www.football-data.co.uk/mmz4281/2122/E1.csv
##### https://www.football-data.co.uk/mmz4281/2122/E2.csv
##### https://www.football-data.co.uk/mmz4281/2122/E3.csv
##### https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [8]:
# creating a list of leagues
leagues = ['E0' , 'E1' , 'E2' , 'E3' , 'EC']
frames = []

# looping through leagues, read multiple CSVs and append it into list
for league in leagues:
    df = pd.read_csv( root + '/2122' + '/' + league + '.csv' , encoding = 'unicode_escape')
    frames.append(df)

In [9]:
# Show combined DataFrame from 5 links
frames

[    ï»¿Div        Date   Time        HomeTeam        AwayTeam  FTHG  FTAG FTR  \
 0       E0  13/08/2021  20:00       Brentford         Arsenal     2     0   H
 1       E0  14/08/2021  12:30      Man United           Leeds     5     1   H
 2       E0  14/08/2021  15:00         Burnley        Brighton     1     2   A
 3       E0  14/08/2021  15:00         Chelsea  Crystal Palace     3     0   H
 4       E0  14/08/2021  15:00         Everton     Southampton     3     1   H
 ..     ...         ...    ...             ...             ...   ...   ...  ..
 375     E0  22/05/2022  16:00  Crystal Palace      Man United     1     0   H
 376     E0  22/05/2022  16:00       Leicester     Southampton     4     1   H
 377     E0  22/05/2022  16:00       Liverpool          Wolves     3     1   H
 378     E0  22/05/2022  16:00        Man City     Aston Villa     3     2   H
 379     E0  22/05/2022  16:00         Norwich       Tottenham     0     5   A

      HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       1     0  ...     1.62  0.50      1.75      2.05   1.81   2.13
 1       1     0  ...     2.25 -1.00      2.05      1.75   2.17   1.77
 2       1     0  ...     1.62  0.25      1.79      2.15   1.81   2.14
 3       2     0  ...     1.94 -1.50      2.05      1.75   2.12   1.81
 4       0     1  ...     1.67 -0.50      2.05      1.88   2.05   1.88
 ..    ...   ...  ...      ...   ...       ...       ...    ...    ...
 375     1     0  ...     2.04  0.25      1.68      2.15   1.74   2.23
 376     0     0  ...     2.63 -0.75      1.83      2.07   1.88   2.03
 377     1     1  ...     3.28 -2.50      2.02      1.77   2.06   1.83
 378     0     1  ...     3.36 -2.25      2.06      1.84   2.05   1.86
 379     0     2  ...     2.40  1.50      1.95      1.95   1.96   1.94

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       2.05     2.17     1.80     2.09
 1       2.19     1.93     2.10     1.79
 2       1.82     2.19     1.79     2.12
 3       2.16     1.93     2.06     1.82
 4       2.08     1.90     2.03     1.86
 ..       ...      ...      ...      ...
 375     1.88     2.25     1.74     2.16
 376     1.94     2.26     1.87     2.01
 377     2.19     1.99     2.07     1.80
 378     2.09     2.03     2.01     1.87
 379     2.16     1.98     1.99     1.89

 [380 rows x 106 columns],
     Div        Date   Time          HomeTeam       AwayTeam  FTHG  FTAG FTR  \
 0    E1  06/08/2021  19:45       Bournemouth      West Brom     2     2   D
 1    E1  07/08/2021  15:00         Blackburn        Swansea     2     1   H
 2    E1  07/08/2021  15:00      Bristol City      Blackpool     1     1   D
 3    E1  07/08/2021  15:00           Cardiff       Barnsley     1     1   D
 4    E1  07/08/2021  15:00             Derby   Huddersfield     1     1   D
 ..   ..         ...    ...               ...            ...   ...   ...  ..
 547  E1  07/05/2022  12:30           Preston  Middlesbrough     4     1   H
 548  E1  07/05/2022  12:30  Sheffield United         Fulham     4     0   H
 549  E1  07/05/2022  12:30             Stoke       Coventry     1     1   D
 550  E1  07/05/2022  12:30           Swansea            QPR     0     1   A
 551  E1  07/05/2022  12:30         West Brom       Barnsley     4     0   H

      HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       1     1  ...     1.84 -0.25      2.13      1.78   2.13   1.80
 1       1     0  ...     1.70 -0.25      1.77      2.14   1.83   2.09
 2       1     0  ...     1.66 -0.25      1.90      2.00   1.92   1.99
 3       0     0  ...     1.62 -0.25      2.05      1.75   2.14   1.80
 4       1     1  ...     1.60 -0.25      1.88      2.02   1.88   2.01
 ..    ...   ...  ...      ...   ...       ...       ...    ...    ...
 547     2     0  ...     2.15  0.75      1.84      2.06   1.88   2.03
 548     3     0  ...     2.09 -0.25      1.75      2.05   1.79   2.12
 549     1     1  ...     2.15 -0.25      1.91      1.99   1.95   1.95
 550     0     0  ...     2.71 -0.50      1.92      1.98   1.94   1.96
 551     2     0  ...     2.67 -1.75      1.88      2.02   1.91   1.98

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       2.16     1.83     2.09     1.77
 1       1.87     2.17     1.81     2.04
 2       1.92     2.01     1.89     1.95
 3       2.19     1.80     2.11     1.75
 4       1.90     2.07     1.87     1.98
 ..       ...      ...      ...      ...
 547     2.00     2.09     1.89     1.96
 548     1.85     2.13     1.81     2.03
 549     1.95     2.01     1.90     1.95
 550     2.00     1.99     1.95     1.90
 551     1.99     2.06     1.90     1.95

 [552 rows x 106 columns],
     Div        Date   Time        HomeTeam            AwayTeam  FTHG  FTAG  \
 0    E2  07/08/2021  15:00          Bolton  Milton Keynes Dons     3     3
 1    E2  07/08/2021  15:00       Cambridge              Oxford     1     1
 2    E2  07/08/2021  15:00           Crewe          Cheltenham     1     1
 3    E2  07/08/2021  15:00       Doncaster       AFC Wimbledon     1     2
 4    E2  07/08/2021  15:00  Fleetwood Town          Portsmouth     0     1
 ..   ..         ...    ...             ...                 ...   ...   ...
 547  E2  30/04/2022  12:30       Morecambe          Sunderland     0     1
 548  E2  30/04/2022  12:30          Oxford           Doncaster     1     1
 549  E2  30/04/2022  12:30        Plymouth  Milton Keynes Dons     0     5
 550  E2  30/04/2022  12:30  Sheffield Weds          Portsmouth     4     1
 551  E2  30/04/2022  12:30      Shrewsbury               Wigan     0     3

     FTR  HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0     D     1     1  ...     1.97 -0.25      1.90      1.95   1.91   1.97
 1     D     0     1  ...     1.86  0.25      2.08      1.73   2.12   1.78
 2     D     1     1  ...     1.69 -0.25      2.00      1.85   1.99   1.90
 3     A     0     0  ...     1.88 -0.25      2.10      1.77   2.11   1.80
 4     A     0     0  ...     1.60  0.00      2.05      1.80   2.09   1.82
 ..   ..   ...   ...  ...      ...   ...       ...       ...    ...    ...
 547   A     0     1  ...     2.09  0.75      2.05      1.80   2.05   1.84
 548   D     1     0  ...     3.05 -1.50      1.90      1.95   1.96   1.93
 549   A     0     3  ...     1.94  0.25      1.83      2.02   1.81   2.09
 550   H     3     1  ...     2.04 -1.00      1.73      2.15   1.76   2.14
 551   A     0     1  ...     1.73  0.50      1.95      1.90   1.97   1.92

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       1.99     2.01     1.90     1.92
 1       2.12     1.82     2.06     1.77
 2       2.04     1.95     1.96     1.87
 3       2.12     1.82     2.07     1.77
 4       2.13     1.86     2.07     1.78
 ..       ...      ...      ...      ...
 547     2.09     1.86     2.02     1.81
 548     2.00     1.99     1.92     1.88
 549     1.88     2.09     1.81     2.02
 550     1.90     2.21     1.77     2.07
 551     2.02     1.94     1.94     1.87

 [552 rows x 106 columns],
     Div        Date   Time        HomeTeam      AwayTeam  FTHG  FTAG FTR  \
 0    E3  07/08/2021  15:00        Carlisle    Colchester     0     0   D
 1    E3  07/08/2021  15:00          Exeter      Bradford     0     0   D
 2    E3  07/08/2021  15:00    Forest Green        Sutton     2     1   H
 3    E3  07/08/2021  15:00       Harrogate      Rochdale     3     2   H
 4    E3  07/08/2021  15:00      Hartlepool  Crawley Town     1     0   H
 ..   ..         ...    ...             ...           ...   ...   ...  ..
 547  E3  07/05/2022  15:00       Mansfield  Forest Green     2     2   D
 548  E3  07/05/2022  15:00  Newport County      Rochdale     0     2   A
 549  E3  07/05/2022  15:00          Oldham  Crawley Town     3     3   D
 550  E3  07/05/2022  15:00       Stevenage       Salford     4     2   H
 551  E3  07/05/2022  15:00         Walsall       Swindon     0     3   A

      HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       0     0  ...     1.57 -0.25      1.75      2.05   1.78   2.13
 1       0     0  ...     1.65  0.00      1.80      2.05   1.79   2.12
 2       1     0  ...     1.60 -0.25      1.98      1.83   1.93   1.95
 3       2     1  ...     1.78 -0.25      1.90      1.95   1.90   1.98
 4       0     0  ...     1.68 -0.25      1.90      1.95   1.93   1.95
 ..    ...   ...  ...      ...   ...       ...       ...    ...    ...
 547     1     0  ...     2.07 -0.25      1.80      2.05   1.84   2.06
 548     0     1  ...     2.21 -0.50      1.88      1.98   1.88   2.02
 549     2     2  ...     2.30  0.00      1.90      1.95   1.89   2.00
 550     2     1  ...     2.01  0.00      1.85      2.00   1.88   2.01
 551     0     3  ...     2.07  0.75      1.98      1.88   1.97   1.92

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       1.82     2.13     1.75     2.08
 1       1.87     2.12     1.80     2.03
 2       2.03     1.99     1.91     1.90
 3       1.94     1.98     1.88     1.94
 4       1.96     1.98     1.90     1.91
 ..       ...      ...      ...      ...
 547     1.91     2.06     1.85     1.97
 548     1.96     2.02     1.90     1.91
 549     1.99     2.02     1.91     1.91
 550     1.97     2.04     1.89     1.92
 551     2.02     1.98     1.91     1.91

 [552 rows x 106 columns],
     Div        Date   Time        HomeTeam      AwayTeam  FTHG  FTAG FTR  \
 0    EC  21/08/2021  15:00       Aldershot  Chesterfield     0     2   A
 1    EC  21/08/2021  15:00          Barnet  Notts County     0     5   A
 2    EC  21/08/2021  15:00         Halifax    Maidenhead     1     2   A
 3    EC  21/08/2021  15:00     Kings Lynn      Southend     0     1   A
 4    EC  21/08/2021  15:00        Solihull       Wrexham     2     2   D
 ..   ..         ...    ...             ...           ...   ...   ...  ..
 501  EC  15/05/2022  15:00  Dover Athletic      Weymouth     1     2   A
 502  EC  15/05/2022  15:00       Eastleigh       Grimsby     4     4   D
 503  EC  15/05/2022  15:00      Maidenhead  Notts County     0     1   A
 504  EC  15/05/2022  15:00        Southend       Torquay     1     1   D
 505  EC  15/05/2022  15:00       Stockport       Halifax     2     0   H

      HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       0     0  ...     1.93  0.50      1.98      1.83   2.03   1.83
 1       0     0  ...     2.06  0.75      1.88      1.93   1.90   1.95
 2       1     0  ...     1.94 -0.50      1.93      1.88   1.99   1.87
 3       0     1  ...     1.91  0.25      1.75      2.05   1.81   2.06
 4       1     2  ...     1.85  0.00      2.05      1.75   1.93   1.92
 ..    ...   ...  ...      ...   ...       ...       ...    ...    ...
 501     0     1  ...     2.50  0.25      1.88      1.93   1.87   1.98
 502     0     2  ...     2.30  0.50      1.88      1.93   1.88   1.98
 503     0     0  ...     2.42  0.50      1.95      1.85   2.03   1.83
 504     0     1  ...     2.01 -0.25      2.02      1.77   2.03   1.83
 505     1     0  ...     1.97 -0.75      1.80      2.00   1.79   2.08

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       2.05     1.90     1.97     1.80
 1       2.00     1.95     1.90     1.88
 2       2.03     1.93     1.94     1.84
 3       1.90     2.11     1.76     2.02
 4       2.05     1.98     1.92     1.86
 ..       ...      ...      ...      ...
 501     1.90     1.98     1.85     1.93
 502     1.95     1.98     1.87     1.90
 503     2.03     1.96     1.92     1.87
 504     2.07     1.85     2.00     1.80
 505     1.93     2.08     1.84     1.95

 [506 rows x 98 columns]]

In [10]:
# length of frames
len(frames)
# 5 - representing 5 links

5

In [11]:
# show 1st element
frames[0]

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [12]:
# show 5th element
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,EC,21/08/2021,15:00,Aldershot,Chesterfield,0,2,A,0,0,...,1.93,0.50,1.98,1.83,2.03,1.83,2.05,1.90,1.97,1.80
1,EC,21/08/2021,15:00,Barnet,Notts County,0,5,A,0,0,...,2.06,0.75,1.88,1.93,1.90,1.95,2.00,1.95,1.90,1.88
2,EC,21/08/2021,15:00,Halifax,Maidenhead,1,2,A,1,0,...,1.94,-0.50,1.93,1.88,1.99,1.87,2.03,1.93,1.94,1.84
3,EC,21/08/2021,15:00,Kings Lynn,Southend,0,1,A,0,1,...,1.91,0.25,1.75,2.05,1.81,2.06,1.90,2.11,1.76,2.02
4,EC,21/08/2021,15:00,Solihull,Wrexham,2,2,D,1,2,...,1.85,0.00,2.05,1.75,1.93,1.92,2.05,1.98,1.92,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,EC,15/05/2022,15:00,Dover Athletic,Weymouth,1,2,A,0,1,...,2.50,0.25,1.88,1.93,1.87,1.98,1.90,1.98,1.85,1.93
502,EC,15/05/2022,15:00,Eastleigh,Grimsby,4,4,D,0,2,...,2.30,0.50,1.88,1.93,1.88,1.98,1.95,1.98,1.87,1.90
503,EC,15/05/2022,15:00,Maidenhead,Notts County,0,1,A,0,0,...,2.42,0.50,1.95,1.85,2.03,1.83,2.03,1.96,1.92,1.87
504,EC,15/05/2022,15:00,Southend,Torquay,1,1,D,0,1,...,2.01,-0.25,2.02,1.77,2.03,1.83,2.07,1.85,2.00,1.80
505,EC,15/05/2022,15:00,Stockport,Halifax,2,0,H,1,0,...,1.97,-0.75,1.80,2.00,1.79,2.08,1.93,2.08,1.84,1.95

# 2.2 Multiple Seasons

In [13]:
# Seasons of (20___) - (20__+1)
for season in range(15 , 21):
     print(str(season) + str(season+1))  # making season str to do concatenation

1516
1617
1718
1819
1920
2021

In [14]:
# creating a list of leagues
leagues = ['E0' , 'E2' , 'E3' ]
frames = []

# looping through leagues, read multiple CSVs and append them to a list
for league in leagues:
    for season in range(15 , 21):
        df = pd.read_csv( root + str(season) + str(season+1)  + '/' + league + '.csv' , encoding = 'unicode_escape')
        df.insert(1 , 'season' , season )
        frames.append(df)

# deleted few leagues to make data less crowded

In [15]:
# total frames (6 seasons x 3 leagues)
len(frames)

18

In [17]:
# show 1st , and last element (new season column was created)
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

# 3 Organize all the data in a Dictionary

In [22]:
# create a dictionary with original name of league as key
dict_countries = {
    'Spanish La Liga':'SP1' , 'Spanish Segunda Division' : 'SP2','German Bundesliga':'D1',
    'English Premier League':'E0' , 'English League 1 ': 'E1' , 'English League 2' : 'E2'
}

In [20]:
# get a dictionary element
dict_countries['Spanish La Liga']

'SP1'

In [24]:
for league in dict_countries:
    print(dict_countries[league])    # ---> to print value
#   print(league)    --> to print key

SP1
SP2
D1
E0
E1
E2

In [26]:
dict_historical_data={}

#creating list of leagues
# leagues = ['E0' , 'E01' , 'E02']


# looping through leagues, read multiple CSVs and append them to a list
for league in dict_countries:
    frames = [] 
    for season in range(15 , 21):
        df = pd.read_csv( root + str(season) + str(season+1)  + '/' + dict_countries[league] + '.csv' , encoding = 'unicode_escape')
        df.insert(1 , 'season' , season )
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league]= df_concat

In [30]:
# show dataframe inside dict_historical_data
dict_historical_data['English Premier League']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,Liverpool,Crystal Palace,2,0,H,1,0,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,Man City,Everton,5,0,H,2,0,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,Sheffield United,Burnley,1,0,H,1,0,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,West Ham,Southampton,3,0,H,2,0,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,Wolves,Man United,1,2,A,1,2,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88